# Generated by Django 2.1.15 on 2022-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='User',
            new_name='user',
        ),
    ]
